name: Build, Lint, and Test

on:
  push:
    branches:
    - "*"
  pull_request:
    branches: [ master ]

jobs:
  # The "build" workflow
  get_source:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
  build_and_test:
    uses: cscoding21/cscoding/.github/workflows/go-build.yaml@main

